unit test: Fix protobuf message comparison
Use the MessageDifferencer to compare protobuf messages instead of the
`==` operator.

```
In file included from /usr/include/boost/test/test_tools.hpp:46,
                 from /work/fts3/test/unit/msg-bus/MsgBus.cpp:18:
/usr/include/boost/test/tools/old/impl.hpp: In instantiation of ‘boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl(const Left&, const Right&) [with Left = fts3::events::Message; Right = fts3::events::Message]’:
/usr/include/boost/test/tools/old/impl.hpp:130:26:   required from ‘boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::call_impl(const Left&, const Right&, mpl_::false_) const [with Left = fts3::events::Message; Right = fts3::events::Message; mpl_::false_ = mpl_::bool_<false>]’
  130 |         return equal_impl( left, right );
      |                ~~~~~~~~~~^~~~~~~~~~~~~~~
/usr/include/boost/test/tools/old/impl.hpp:145:25:   required from ‘boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::operator()(const Left&, const Right&) const [with Left = fts3::events::Message; Right = fts3::events::Message]’
  145 |         return call_impl( left, right, left_is_array() );
      |                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/test/tools/old/impl.hpp:92:1:   required from ‘bool boost::test_tools::tt_detail::check_frwd(Pred, const boost::unit_test::lazy_ostream&, boost::unit_test::const_string, std::size_t, tool_level, check_type, const Arg0&, const char*, const Arg1&, const char*) [with Pred = equal_impl_frwd; Arg0 = fts3::events::Message; Arg1 = fts3::events::Message; boost::unit_test::const_string = boost::unit_test::basic_cstring<const char>; std::size_t = long unsigned int]’
   92 | BOOST_PP_REPEAT( BOOST_TEST_MAX_PREDICATE_ARITY, IMPL_FRWD, _ )
      | ^~~~~~~~~~~~~~~
/fts3/test/unit/msg-bus/MsgBus.cpp:112:5:   required from here
  112 |     BOOST_CHECK_EQUAL(statuses[0], original);
      |     ^~~~~~~~~~~~~~~~~
/usr/include/boost/test/tools/old/impl.hpp:107:17: error: no match for ‘operator==’ (operand types are ‘const fts3::events::Message’ and ‘const fts3::events::Message’)
  107 |     return left == right;
      |            ~~~~~^~~~~~~~
```