Add missing headers, fixes compilation error
```
In file included from /fts3/src/url-copy/heuristics.cpp:21:
/fts3/src/url-copy/heuristics.h:35:35: error: ‘uint64_t’ was not declared in this scope
   35 | unsigned adjustTimeoutBasedOnSize(uint64_t sizeInBytes, unsigned addSecPerMb);
      |                                   ^~~~~~~~
/fts3/src/url-copy/heuristics.h:25:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   24 | #include <string>
  +++ |+#include <cstdint>
   25 |
/fts3/src/url-copy/heuristics.h:35:57: error: expected primary-expression before ‘unsigned’
   35 | unsigned adjustTimeoutBasedOnSize(uint64_t sizeInBytes, unsigned addSecPerMb);
      |                                                         ^~~~~~~~
/fts3/src/url-copy/heuristics.h:35:77: error: expression list treated as compound expression in initializer [-fpermissive]
   35 | unsigned adjustTimeoutBasedOnSize(uint64_t sizeInBytes, unsigned addSecPerMb);
      |                                                                             ^
[ 44%] Building CXX object src/db/mysql/CMakeFiles/fts_db_mysql.dir/Config.cpp.o
/fts3/src/url-copy/heuristics.cpp:143:83: error: ‘unsigned int adjustTimeoutBasedOnSize(uint64_t, unsigned int)’ redeclared as different kind of entity
  143 | unsigned adjustTimeoutBasedOnSize(uint64_t sizeInBytes, const unsigned addSecPerMb)
      |                                                                                   ^
/fts3/src/url-copy/heuristics.h:35:10: note: previous declaration ‘unsigned int adjustTimeoutBasedOnSize’
   35 | unsigned adjustTimeoutBasedOnSize(uint64_t sizeInBytes, unsigned addSecPerMb);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
```